### ISSUE TITLE
Sorry to ask random questions, but how to use demoji.replace()?

### ISSUE THREAD

**Issue by bboczeng** [bsolomon1124/demoji#1]
Why the tutorial only gives example of demoji.findall()?
What about the other major function replace()?

**Comment by mgalla16-sn4g** [comment]
https://github.com/bsolomon1124/demoji/blob/f28ffba0a5c9688b8f50f7d5712461e092890824/demoji/__init__.py#L196 explains it pretty well. It takes a string and a replacement, defaults to empty if none specified.
ex:
```
import demoji
test_str = "game🔥🔥"
new_str = demoji.replace(test_str)
#new_str would now be "game"
```
