### ISSUE TITLE
demji returns local datetime as utc datetime

### ISSUE THREAD

**Issue by 1-1is0** [bsolomon1124/demoji#15]
when calling `demoji.last_downloaded_timestamp()` it returns a timeaware object of system localtime zone instead utc time
which is incorrect in **UTC** time.

**To Reproduce**

```python
>>> demoji.last_downloaded_timestamp()
datetime.datetime(2020, 10, 26, 11, 21, 57, 347238, tzinfo=<demoji.UTC object at 0x7fab3f849eb0>)
>>> datetime.utcnow()
datetime.datetime(2020, 10, 26, 7, 58, 53, 767124)
>>> datetime.now()
datetime.datetime(2020, 10, 26, 11, 28, 54, 955153)
```

**Desktop**
 - OS: Ubuntu 20.04
 - Version: '0.3.0'
 - Python: 3.8.5
 - My local timezone: ('Asia/Tehran') UTC+3:30

**Comment by bsolomon1124** [comment]
Thank you for catching this. The timestamp is written with `time.time()` (time in seconds since the epoch as a floating point number) but then loaded back with `datetime.fromtimestamp()`, which should be `datetime.utcfromtimestamp()`.
