### ISSUE TITLE
Replace endpoint for static URL

### ISSUE THREAD

**Issue by Vilmorq** [bsolomon1124/demoji#16]
Hello. Thanks for your app.

Good idea to replace download endpoint's url with a permanent one. You are working with 12.0, but 13.1 is available. So, let's use "unicode.org/Public/emoji/latest/emoji-test.txt" ?)

**Comment by bsolomon1124** [comment]
I'm open to this but it looks like 13.0 introduced codes into the descriptions.  For instance, previous was:

```
1F600                                      ; fully-qualified     # 😀 grinning face
```

and in 13 is now

```
1F600                                                  ; fully-qualified     # 😀 E1.0 grinning face
```

**Comment by bsolomon1124** [comment]
I am going to upgrade to 13.1 but keep the version hardcoded rather than using the dynamic 'latest'. Thanks for your suggestion, but I also want to balance the need for stability rather than assuming that a dynamically updating list will maintain the same format.
