### ISSUE TITLE
Fix colors in Windows console

### ISSUE THREAD

**Issue by alexgoryushkin** [bsolomon1124/demoji#5]
Windows cmd not support escape sequences by default. But it can be fixed:
```python3
import sys
import demoji

if ('win' in sys.platform):
    import ctypes
    kernel32 = ctypes.windll.kernel32
    kernel32.SetConsoleMode(kernel32.GetStdHandle(-11), 7)

demoji.download_codes()
```

Output before:
![image](https://user-images.githubusercontent.com/43167451/77513756-6b726e80-6e97-11ea-88ff-79f2f3f85797.png)

Output after:
![image](https://user-images.githubusercontent.com/43167451/77513838-8d6bf100-6e97-11ea-8bf1-f4a06d9435ea.png)

**Comment by bsolomon1124** [comment]
Thanks for bringing this up - I'm going to add https://pypi.org/project/colorama/ which addresses this specifically.  (Cool ctypes trick though 😄 )

**Comment by bsolomon1124** [comment]
Please let me know if upgrading `demoji` does not solve this issue for you @alexgoryushkin .  Thanks!
