### ISSUE TITLE
Can you add tags for the releases?

### ISSUE THREAD

**Issue by trygveaa** [bsolomon1124/demoji#6]
I want to upload this library to the [Arch user repository](https://aur.archlinux.org/), and to do so it would be practical to have git tags for the releases, or at least for the most current release and future releases. Could you add that?

I.e. run these git commands
```
git tag -a -m 'Release v0.1.5' v0.1.5 f28ffba
git push --follow-tags
```

**Comment by bsolomon1124** [comment]
Done @trygveaa: https://github.com/bsolomon1124/demoji/releases. Please let me know if anything is amiss and I can re-open.

**Comment by trygveaa** [comment]
Thanks! I created this package https://aur.archlinux.org/packages/python-demoji/

**Comment by bsolomon1124** [comment]
@trygveaa Okay, just want to make sure you're aware that `colorama` and `requests` [are formal dependencies](https://github.com/bsolomon1124/demoji/blob/480ce621ed402fa24e2832bbda66df6a9f49c751/setup.py#L52). I'm not super familiar with Linux package distribution - does that need to be specified anywhere?

**Comment by trygveaa** [comment]
Yes, they are specified [here](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=python-demoji#n10):

    depends=('python-requests' 'python-colorama')

I'm not sure why they are not listed under "Dependencies" on https://aur.archlinux.org/packages/python-demoji/ though, I'll have to check that out. My package manager detects the dependencies correctly, so it should work even though they're not listed there.

**Comment by trygveaa** [comment]
I had an error with the metadata, the web page lists the dependencies now.
